---
name: Build README

on:
  push:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run: echo "Run build script"
