name: Build README

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Personal Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo "Run build script"
